#
# Copyright (c) 2013-2019 Vinnie Falco (vinnie dot falco at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Official repository: https://github.com/boostorg/beast
#

sudo: false
language: cpp
addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test

compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    #- llvm-toolchain-precise-3.9
    packages:
    #- g++-7
    #- clang-3.9
install:
  - "[ $CXX = g++ ] || true"
  - "[ $CXX = clang++ ] || true"
  - cd ..
  - $TRAVIS_BUILD_DIR/tools/get-boost.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR
  - cd boost-root
  - ./bootstrap.sh
  - export BOOST_ROOT=$TRAVIS_BUILD_DIR/../boost-root
  - cd $TRAVIS_BUILD_DIR
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest
notifications:
  email:
    on_success: never
